services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - autoshop-lapis-network
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      LAPIS_SECRET_KEY: ${LAPIS_SECRET_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/app
    networks:
      - autoshop-lapis-network
    entrypoint: ["/bin/bash", "-c"]
    command: ["/usr/local/openresty/luajit/bin/lapis migrate && /usr/local/openresty/luajit/bin/lapis server development"]

volumes:
  pgdata:

networks:
  autoshop-lapis-network: